#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias chrome='open -a Google\ Chrome --args --disable-web-security'
alias update_zprezto='(cd $HOME/.zprezto && git pull && git submodule update --init --recursive)'
alias update_vim='vim +VundleUpdate +qall'

export HISTFILE=$HOME/.zsh_history

fpath=(/usr/local/share/zsh-completions $fpath)

# added for the latest version of zsh
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# add awscli completion
source /usr/local/share/zsh/site-functions/_aws
