#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias chrome='open -a Google\ Chrome --args --disable-web-security'
alias update_zprezto='cd $HOME/.zprezto && git pull && git submodule update --init --recursive'

export HISTFILE=$HOME/.zsh_history

fpath=(/usr/local/share/zsh-completions $fpath)


function pushover {
    curl -s -F "token=arbXj1mWZ5RFScFyxLQwCxM7XAx5qK" \
    -F "user=uhZQBdSaM68HhuPma13gYNk94bVRhX" \
    -F "title=YOUR_TITLE_HERE" \
    -F "message=$1" https://api.pushover.net/1/messages.json
}
